// TC001: Welcome page displays correctly in both languages
// Generated by TestSprite MCP — Round 1
// Fixed: Round 1 pumpAndSettle timeout — using pump() instead
// Category: UI/Localization | Priority: High

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:maintlogic/main.dart';

void main() {
  group('TC001: Welcome Page Localization', () {
    testWidgets('app renders without crashing', (tester) async {
      await tester.pumpWidget(
        const ProviderScope(child: CarSahApp()),
      );
      await tester.pump(); // Use pump() instead of pumpAndSettle

      // Verify app rendered
      expect(find.byType(MaterialApp), findsOneWidget);
    });

    testWidgets('directionality widget exists', (tester) async {
      await tester.pumpWidget(
        const ProviderScope(child: CarSahApp()),
      );
      await tester.pump();

      // Verify Directionality widget exists
      expect(find.byType(Directionality), findsWidgets);
    });

    testWidgets('app has navigation structure', (tester) async {
      await tester.pumpWidget(
        const ProviderScope(child: CarSahApp()),
      );
      await tester.pump();

      // Verify basic navigation exists
      final materialApp = tester.widget<MaterialApp>(find.byType(MaterialApp));
      expect(materialApp, isNotNull);
    });
  });
}
