// TC008: Service task CRUD operations
// Generated by TestSprite MCP — Round 1
// Fixed: Round 1 discovered actual model structure
// Category: Maintenance | Priority: High

import 'package:flutter_test/flutter_test.dart';
import 'package:maintlogic/data/models/service_task.dart';

void main() {
  group('TC008: Service Task CRUD', () {
    test('create service task with all fields', () {
      final task = ServiceTask(
        vehicleId: 1,
        taskKey: 'tire_rotation',
        displayNameAr: 'تدوير الإطارات',
        displayNameEn: 'Tire Rotation',
        intervalKm: 10000,
        intervalMonths: 12,
      );

      expect(task.taskKey, equals('tire_rotation'));
      expect(task.intervalKm, equals(10000));
      expect(task.intervalMonths, equals(12));
    });

    test('service task key should be unique identifier', () {
      final task = ServiceTask(
        vehicleId: 1,
        taskKey: 'oil_change_5w30',
        displayNameAr: 'تغيير الزيت',
        displayNameEn: 'Oil Change',
      );

      // Task key should be a stable identifier
      expect(task.taskKey, isNotEmpty);
      expect(task.taskKey, contains('oil_change'));
    });

    test('service task links to vehicle via vehicleId', () {
      final task = ServiceTask(
        vehicleId: 42,
        taskKey: 'brake_inspection',
        displayNameAr: 'فحص الفرامل',
        displayNameEn: 'Brake Inspection',
      );

      expect(task.vehicleId, equals(42));
    });
  });
}
