// TC006: Multiple vehicle management
// Generated by TestSprite MCP — Round 1
// Category: Vehicle Management | Priority: Medium

import 'package:flutter_test/flutter_test.dart';
import 'package:maintlogic/data/models/vehicle.dart';

void main() {
  group('TC006: Multiple Vehicles', () {
    test('each vehicle has unique identity', () {
      final vehicle1 = Vehicle()
        ..make = 'Tank 300'
        ..currentMileage = 15000;

      final vehicle2 = Vehicle()
        ..make = 'Toyota Camry'
        ..currentMileage = 50000;

      expect(vehicle1.make, isNot(equals(vehicle2.make)));
      expect(vehicle1.currentMileage, isNot(equals(vehicle2.currentMileage)));
    });

    test('vehicle mileage can be updated independently', () {
      final vehicle = Vehicle()
        ..make = 'Tank 300'
        ..currentMileage = 15000;

      vehicle.currentMileage = 16000;
      expect(vehicle.currentMileage, equals(16000));
    });
  });
}
