// TC005: Task completion and history tracking
// Generated by TestSprite MCP — Round 1
// Fixed: Round 1 discovered actual field names
// Category: Maintenance | Priority: High

import 'package:flutter_test/flutter_test.dart';
import 'package:maintlogic/data/models/maintenance_record.dart';

void main() {
  group('TC005: Task Completion', () {
    test('maintenance record captures completion data', () {
      final record = MaintenanceRecord(
        vehicleId: 1,
        serviceType: 'Oil Change',
        odometerKm: 20000,
        totalCostSar: 150.0,
        serviceDate: DateTime(2026, 4, 16),
      );

      expect(record.serviceType, equals('Oil Change'));
      expect(record.totalCostSar, equals(150.0));
      expect(record.odometerKm, equals(20000));
    });

    test('maintenance record has cost breakdown fields', () {
      final record = MaintenanceRecord(
        vehicleId: 1,
        serviceType: 'Full Service',
        odometerKm: 30000,
        totalCostSar: 500.0,
        serviceDate: DateTime.now(),
        partsCostSar: 300.0,
        laborCostSar: 200.0,
      );

      expect(record.partsCostSar, equals(300.0));
      expect(record.laborCostSar, equals(200.0));
      expect(record.totalCostSar, equals(500.0));
    });

    test('maintenance record can track parts replaced', () {
      final record = MaintenanceRecord(
        vehicleId: 1,
        serviceType: 'Oil Change',
        odometerKm: 20000,
        totalCostSar: 150.0,
        serviceDate: DateTime.now(),
        partsReplaced: ['Oil Filter', 'Engine Oil 5W-30'],
      );

      expect(record.partsReplaced, isNotNull);
      expect(record.partsReplaced!.length, equals(2));
    });
  });
}
