// TC003: Maintenance task scheduling
// Generated by TestSprite MCP — Round 1
// Fixed: Round 1 discovered required vehicleId parameter
// Category: Maintenance | Priority: High

import 'package:flutter_test/flutter_test.dart';
import 'package:maintlogic/data/models/service_task.dart';

void main() {
  group('TC003: Maintenance Scheduling', () {
    test('service task has mileage and time intervals', () {
      final task = ServiceTask(
        vehicleId: 1,
        taskKey: 'oil_change',
        displayNameAr: 'تغيير الزيت',
        displayNameEn: 'Oil Change',
        intervalKm: 5000,
        intervalMonths: 6,
      );

      expect(task.taskKey, equals('oil_change'));
      expect(task.displayNameEn, equals('Oil Change'));
      expect(task.displayNameAr, equals('تغيير الزيت'));
      expect(task.intervalKm, equals(5000));
      expect(task.intervalMonths, equals(6));
    });

    test('service task supports bilingual names', () {
      final task = ServiceTask(
        vehicleId: 1,
        taskKey: 'tire_rotation',
        displayNameAr: 'تدوير الإطارات',
        displayNameEn: 'Tire Rotation',
        intervalKm: 10000,
      );

      expect(task.displayNameAr, isNotEmpty);
      expect(task.displayNameEn, isNotEmpty);
    });

    test('interval can be null for flexible scheduling', () {
      final task = ServiceTask(
        vehicleId: 1,
        taskKey: 'custom_task',
        displayNameAr: 'مهمة مخصصة',
        displayNameEn: 'Custom Task',
      );

      expect(task.intervalKm, isNull);
      expect(task.intervalMonths, isNull);
    });
  });
}
