// TC009: Dashboard summary accuracy
// Generated by TestSprite MCP — Round 1
// Category: Dashboard | Priority: High

import 'package:flutter_test/flutter_test.dart';

void main() {
  group('TC009: Dashboard Summary', () {
    test('overdue task count calculation', () {
      final now = DateTime.now();
      final tasks = [
        {'dueDate': now.subtract(const Duration(days: 5)), 'name': 'Oil Change'},
        {'dueDate': now.subtract(const Duration(days: 10)), 'name': 'Tire Rotation'},
        {'dueDate': now.add(const Duration(days: 5)), 'name': 'Brake Check'},
      ];

      final overdue = tasks.where((t) =>
        (t['dueDate'] as DateTime).isBefore(now)
      ).length;

      expect(overdue, equals(2));
    });

    test('upcoming task count calculation', () {
      final now = DateTime.now();
      final tasks = [
        {'dueDate': now.add(const Duration(days: 5)), 'name': 'Oil Change'},
        {'dueDate': now.add(const Duration(days: 30)), 'name': 'Tire Rotation'},
        {'dueDate': now.subtract(const Duration(days: 5)), 'name': 'Brake Check'},
      ];

      final upcoming = tasks.where((t) =>
        (t['dueDate'] as DateTime).isAfter(now)
      ).length;

      expect(upcoming, equals(2));
    });

    test('empty task list returns zero counts', () {
      final tasks = <Map<String, dynamic>>[];
      expect(tasks.length, equals(0));
    });
  });
}
