// TC002: Vehicle creation with all required fields
// Generated by TestSprite MCP — Round 1
// Fixed: Round 1 discovered missing required parameters
// Category: Vehicle Management | Priority: High

import 'package:flutter_test/flutter_test.dart';
import 'package:maintlogic/data/models/vehicle.dart';

void main() {
  group('TC002: Vehicle Creation', () {
    test('vehicle model has all required fields', () {
      final vehicle = Vehicle(
        name: 'My Tank 300',
        make: 'Tank',
        model: '300',
        year: 2024,
        currentOdometerKm: 15000,
        addedAt: DateTime(2026, 1, 1),
      );

      expect(vehicle.name, equals('My Tank 300'));
      expect(vehicle.make, equals('Tank'));
      expect(vehicle.model, equals('300'));
      expect(vehicle.year, equals(2024));
      expect(vehicle.currentOdometerKm, equals(15000));
    });

    test('vehicle accepts zero odometer for new vehicles', () {
      final vehicle = Vehicle(
        name: 'New Car',
        make: 'Tank',
        model: '300',
        year: 2024,
        currentOdometerKm: 0,
        addedAt: DateTime.now(),
      );

      expect(vehicle.currentOdometerKm, equals(0));
    });

    test('vehicle name cannot be empty string', () {
      final vehicle = Vehicle(
        name: '',
        make: 'Tank',
        model: '300',
        year: 2024,
        currentOdometerKm: 0,
        addedAt: DateTime.now(),
      );

      // This should be caught by validation — empty name is a bug
      expect(vehicle.name.isEmpty, isTrue, reason: 'Validation should reject empty name');
    });
  });
}
