// TC010: Data persistence across app restarts
// Generated by TestSprite MCP — Round 1
// Fixed: Round 1 discovered actual field names
// Category: Data Persistence | Priority: High

import 'package:flutter_test/flutter_test.dart';
import 'package:maintlogic/data/models/vehicle.dart';
import 'package:maintlogic/data/models/service_task.dart';
import 'package:maintlogic/data/models/maintenance_record.dart';

void main() {
  group('TC010: Data Persistence', () {
    test('vehicle model has Isar auto-increment ID', () {
      final vehicle = Vehicle(
        name: 'Tank 300',
        make: 'Tank',
        model: '300',
        year: 2024,
        currentOdometerKm: 15000,
        addedAt: DateTime.now(),
      );

      expect(vehicle.id, isNotNull);
    });

    test('service task links to vehicle correctly', () {
      final task = ServiceTask(
        vehicleId: 42,
        taskKey: 'oil_change',
        displayNameAr: 'تغيير الزيت',
        displayNameEn: 'Oil Change',
      );

      expect(task.vehicleId, equals(42));
      expect(task.taskKey, equals('oil_change'));
    });

    test('maintenance record has required fields', () {
      final record = MaintenanceRecord(
        vehicleId: 1,
        serviceType: 'Oil Change',
        odometerKm: 20000,
        totalCostSar: 150.0,
        serviceDate: DateTime.now(),
      );

      expect(record.vehicleId, equals(1));
      expect(record.serviceType, equals('Oil Change'));
      expect(record.totalCostSar, equals(150.0));
      expect(record.odometerKm, equals(20000));
    });

    test('maintenance record has sync status', () {
      final record = MaintenanceRecord(
        vehicleId: 1,
        serviceType: 'Oil Change',
        odometerKm: 20000,
        totalCostSar: 150.0,
        serviceDate: DateTime.now(),
      );

      // isSynced defaults to false
      expect(record.isSynced, isFalse);
    });
  });
}
